config/routes.rb
Burroughs::Application.routes.draw do

  resources :buildings do
    resources :building_locations
    resources :sources
    resources :artifacts
  end

  resources :locations do
    resources :sources
    resources :artifacts
  end

  resources :establishments do
    resources :existences
    resources :sources
    resources :artifacts
  end

  resources :existences do
    resources :existence_locations
    resources :sources
    resources :artifacts
  end

  resources :artifacts, only: [:show]

  root to: 'buildings#index'
end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :description, :end_year, :name, :start_year

  has_many :building_locations
  has_many :locations, through: :building_locations
  has_many :existences, through: :locations
  has_many :sources, as: :sourceable
  has_many :artifacts, as: :artifactable

  validates :name, presence: true

  scope :by_name, lambda { order('name') }
  scope :by_existence_years, lambda { order("start_year, end_year") }

  def fullname
    name + year_range
  end

  private

  def year_range
    range = ''
    if start_year or end_year
      range += ' ('
      if start_year
        range += start_year.to_s
      else
        range += '?'
      end

      if end_year
        range += "-#{end_year.to_s}"
      end
      range += ')'
    end
    range
  end
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController
  layout 'admin'

  admin_assistant_for Building
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def index
    @buildings = Building.by_name.by_existence_years

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  def edit
    @building = Building.find(params[:id])
  end

  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Successfully created building.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Successfully updated building.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/views/buildings/_form.html.haml
= simple_form_for(@building) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :start_year
    = f.input :end_year

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/buildings/edit.html.haml
- content_for(:title) { 'Edit building'}

= render 'form'

app/views/buildings/index.html.haml
- content_for(:title) { 'Buildings' }

%table.table.table-striped.table-hover
  %tr
    %th Name
    %th Locations
    %th From
    %th To

  - @buildings.each do |building|
    %tr
      %td= link_to building.name, building
      %td= building.locations.map(&:address).join(', ')
      %td= building.start_year
      %td= building.end_year

.form-actions
  = link_to 'New Building', new_building_path, class: 'btn btn-primary'

app/views/buildings/new.html.haml
- content_for(:title) { 'New building' }

= render 'form'

app/views/buildings/show.html.haml
- content_for(:title) { @building.fullname }

= simple_format @building.description

%h2 Locations

%table.table.table-striped
  %tr
    %th Address
    %th Latitude
    %th Longitude
    %th
  - @building.building_locations.each do |bl|
    %tr
      %td= link_to bl.location.name, bl.location
      %td= bl.location.latitude
      %td= bl.location.longitude
      %td{ style: 'text-align:right' }
        = link_to 'Edit', [:edit, @building, bl], class: 'btn btn-mini'
        = link_to 'Delete', [@building, bl], method: :delete, class: 'btn btn-mini', confirm: 'Are you sure?'

%p
  = link_to 'New Building Location', new_building_building_location_path(@building), class: 'btn'

%h2 Establishments

= render 'existences/existences', existences: @building.existences

= render 'artifacts/artifacts', artifactable: @building

= render 'sources/sources', sourceable: @building

.form-actions
  = link_to 'Edit', edit_building_path(@building), class: 'btn btn-primary'