config/routes.rb
Burroughs::Application.routes.draw do

  resources :buildings do
    resources :building_locations
    resources :sources
    resources :artifacts
  end

  resources :locations do
    resources :sources
    resources :artifacts
  end

  resources :establishments do
    resources :existences
    resources :sources
    resources :artifacts
  end

  resources :existences do
    resources :existence_locations
    resources :sources
    resources :artifacts
  end

  resources :artifacts, only: [:show]

  root to: 'buildings#index'
end

app/models/existence_location.rb
class ExistenceLocation < ActiveRecord::Base
  belongs_to :existence
  belongs_to :location
  attr_accessible :existence_id, :location_id
end

app/controllers/existence_locations_controller.rb
class ExistenceLocationsController < ApplicationController
  before_filter :get_existence
  before_filter :get_existence_location, except: [:new, :create]

  def new
    @existence_location = @existence.existence_locations.build
  end

  def create
    @existence_location = @existence.existence_locations.new(params[:existence_location])
    if @existence_location.save
      redirect_to @existence_location.existence, notice: 'Successfully created existence/location'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @existence_location.update_attributes(params[:existence_location])
      redirect_to @existence_location.existence, notice: 'Successfully updated existence/location'
    else
      render :edit
    end
  end

  def destroy
    @existence_location.destroy
    redirect_to @existence, notice: 'Successfuly deleted existence/location'
  end

  private

  def get_existence
    @existence = Existence.find(params[:existence_id]) if params[:existence_id]
  end

  def get_existence_location
    if params[:id]
      @existence_location = @existence.existence_locations.find(params[:id])
    end
  end
end

app/helpers/existence_locations_helper.rb
module ExistenceLocationsHelper
end

app/views/existence_locations/_form.html.haml
= simple_form_for [existence_location.existence,existence_location] do |f|
  = f.error_notification

  .form-inputs
    = f.association :location
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Add another location', new_location_path, class: 'btn'

app/views/existence_locations/edit.html.haml
- content_for(:title) { "Edit existence/location for #{@existence.establishment_name}" }

= render 'form', existence_location: @existence_location

app/views/existence_locations/index.html.haml
%h1 Listing existence_locations

%table
  %tr
    %th Existence
    %th Location
    %th
    %th
    %th

  - @existence_locations.each do |existence_location|
    %tr
      %td= existence_location.existence
      %td= existence_location.location
      %td= link_to 'Show', existence_location
      %td= link_to 'Edit', edit_existence_location_path(existence_location)
      %td= link_to 'Destroy', existence_location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Existence location', new_existence_location_path

app/views/existence_locations/new.html.haml
- content_for(:title) { "New existence/location for #{@existence.establishment_name}" }

= render 'form', existence_location: @existence_location

app/views/existence_locations/show.html.haml
%p#notice= notice

%p
  %b Existence:
  = @existence_location.existence
%p
  %b Location:
  = @existence_location.location

= link_to 'Edit', edit_existence_location_path(@existence_location)
\|
= link_to 'Back', existence_locations_path