config/routes.rb
Burroughs::Application.routes.draw do

  resources :buildings do
    resources :building_locations
    resources :sources
    resources :artifacts
  end

  resources :locations do
    resources :sources
    resources :artifacts
  end

  resources :establishments do
    resources :existences
    resources :sources
    resources :artifacts
  end

  resources :existences do
    resources :existence_locations
    resources :sources
    resources :artifacts
  end

  resources :artifacts, only: [:show]

  root to: 'buildings#index'
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
  attr_accessible :description, :end_year, :name, :start_year

  has_many :existences
  has_many :locations, through: :existences
  has_many :sources, as: :sourceable
  has_many :artifacts, as: :artifactable

  validates :name, presence: true

  scope :by_name, lambda { order("name") }
end

app/controllers/admin/establishments_controller.rb
class Admin::EstablishmentsController < ApplicationController
  layout 'admin'

  admin_assistant_for Establishment
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  def index
    @establishments = Establishment.by_name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @establishments }
    end
  end

  def show
    @establishment = Establishment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @establishment }
    end
  end

  def new
    @establishment = Establishment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @establishment }
    end
  end

  def edit
    @establishment = Establishment.find(params[:id])
  end

  def create
    @establishment = Establishment.new(params[:establishment])

    respond_to do |format|
      if @establishment.save
        format.html { redirect_to establishments_url, notice: 'Successfully created establishment.' }
        format.json { render json: @establishment, status: :created, location: @establishment }
      else
        format.html { render action: "new" }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @establishment = Establishment.find(params[:id])

    respond_to do |format|
      if @establishment.update_attributes(params[:establishment])
        format.html { redirect_to @establishment, notice: 'Establishment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @establishment = Establishment.find(params[:id])
    @establishment.destroy

    respond_to do |format|
      format.html { redirect_to establishments_url }
      format.json { head :no_content }
    end
  end
end

app/views/establishments/_form.html.haml
= simple_form_for(@establishment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/establishments/edit.html.haml
- content_for(:title) { 'Edit establishment' }

= render 'form'

app/views/establishments/index.html.haml
- content_for(:title) { 'Establishments' }

%table.table.table-striped.table-hover
  %tr
    %th Name
    %th

  - @establishments.each do |establishment|
    %tr
      %td= link_to establishment.name, establishment
      %td= pluralize(establishment.locations.length, "known location")

.form-actions
  = link_to 'New Establishment', new_establishment_path, class: 'btn btn-primary'

app/views/establishments/new.html.haml
- content_for(:title) { 'New establishment' }

= render 'form'

= link_to 'Back', establishments_path

app/views/establishments/show.html.haml
- content_for(:title) { @establishment.name }

= simple_format @establishment.description

%h2 Existences

%table.table.table-striped.table-hover
  %tr
    %th Start year
    %th End year
    %th Locations
    %th

  - @establishment.existences.by_existence_years.each do |existence|
    %tr
      %td= existence.start_year
      %td= existence.end_year
      %td= existence.locations.map(&:address).join(', ')
      %td{ style: 'text-align: right' }
        = link_to 'Show', existence, class: 'btn btn-mini'
        = link_to 'Edit', edit_establishment_existence_path(@establishment, existence), class: 'btn btn-mini'
        = link_to 'Delete', establishment_existence_path(@establishment, existence), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-mini'


= link_to 'New Existence', new_establishment_existence_path(@establishment), class: 'btn'

= render 'sources/sources', sourceable: @establishment

= render 'artifacts/artifacts', artifactable: @establishment

.form-actions
  = link_to 'Edit', edit_establishment_path(@establishment), class: 'btn btn-primary'
  = link_to 'Delete', @establishment, method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'