config/routes.rb
Burroughs::Application.routes.draw do

  resources :buildings do
    resources :building_locations
    resources :sources
    resources :artifacts
  end

  resources :locations do
    resources :sources
    resources :artifacts
  end

  resources :establishments do
    resources :existences
    resources :sources
    resources :artifacts
  end

  resources :existences do
    resources :existence_locations
    resources :sources
    resources :artifacts
  end

  resources :artifacts, only: [:show]

  root to: 'buildings#index'
end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Burroughs"
    = csrf_meta_tags
    = javascript_include_tag "admin"
    = stylesheet_link_tag 'admin'

  %body
    = yield

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Burroughs"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"

  %body
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Burroughs
          .container.nav-collapse
            %ul.nav
              %li= link_to "Buildings", buildings_path
              %li= link_to "Locations", locations_path
              %li= link_to "Establishments", establishments_path

    .container

      .row
        .span12
          = bootstrap_flash

          %h1= yield(:title)

          = yield

    = javascript_include_tag "application"